### PR TITLE
Give all poems a permalink

### PR DESCRIPTION
**Pull request by nylen**
Changes application URLs and refresh behavior: POST to /poem generates a random seed then redirects to GET /poem/seed or GET /mushypoem/seed

Also a few whitespace fixes + a `.gitignore` file for virtualenv stuff.

### CODE REVIEW

**Comment by nylen** [comment]
You can see this in action at http://nylen.tv/poem (refresh to load the same poem; click the buttons to generate a new poem).

I don't use nginx so I am not sure if further changes would be needed to support this new URL structure there.

**Comment by schollz** [comment]
This is so cool! What a great feature!!
I've tested and it works great with nginx.

Thanks.

**Comment by nylen** [comment]
Very cool program, I'm curious about further enhancements like [n-gram modeling](https://en.wikipedia.org/wiki/N-gram#n-gram_models) but not very knowledgeable in this area :)

I've got a few other changes in my local branch.  Let me know if any/all/none of these interest you, and I can clean up commits and submit another PR:

``` git
commit f09aeda76ee0c84f7992cb0c14948cd4ba05dfce
Author: James Nylen <jnylen@gmail.com>
Date:   Mon Dec 28 21:57:46 2015 -0600

    Remove run.py

    Obsolete now that `python poem.py` works.

commit db662b0ae2873d431752468920143bdc8f011e01
Author: James Nylen <jnylen@gmail.com>
Date:   Mon Dec 28 21:50:35 2015 -0600

    Another typo fix

commit 8fd44bac49a9875b9f865c3ad6ea63258cb37b8f
Author: James Nylen <jnylen@gmail.com>
Date:   Mon Dec 28 21:49:33 2015 -0600

    Fix `python poem.py`

    Move seed generation & display logic from server.py into poem.py

commit 0f610f1e15131ecfa8d3b4480f5558a9d35fdd26
Author: James Nylen <jnylen@gmail.com>
Date:   Mon Dec 28 21:36:36 2015 -0600

    A few typo fixes

commit c0ff31d46dc21ff7f49e52aaeb0d0fe1da7531b8
Author: James Nylen <jnylen@gmail.com>
Date:   Mon Dec 28 21:31:16 2015 -0600

    Set date to December 31 1969

    Or maybe January 1 1970 for some servers ?

    All possible poems generated by this program already exist as Platonic
    ideals.
```

**Comment by schollz** [comment]
Awesome! So I went ahead and cloned your code and added your changes. I had to change the `hex_seed` cause Python3 was complaining about it, so I used `binascii` and `uuid` and it works great.

I like the idea about tuples, I'll think about it too. It should be straightforward to modify the BN syntax to adding optional tuple-like noun/verb/adjectives.

**Comment by schollz** [comment]
Hey, I've been implementing a bunch of new features. I've opened a new branch [1.1](https://github.com/schollz/poetry-generator/tree/1.1). Please let me know if you have any other ideas for enhancements - just open an issue!

**Pull request merged**
